AWSTemplateFormatVersion: 2010-09-09
Description: Book Finder (Cognito auth stack)

Parameters:
  BookFinderUserPoolName:
    Type: String
    Default: "book finder user pool"

  BookFinderClientName:
    Type: String
    Default: "book finder user pool client"

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UserPoolName: !Ref BookFinderUserPoolName

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref BookFinderClientName
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolArn:
    Value: !GetAtt
      - UserPool
      - Arn

  UserPoolClientId:
    Value: !Ref UserPoolClient
