AWSTemplateFormatVersion: 2010-09-09
Description: Lambda uploads (versioning enabled bucket)

Parameters:
  Unique:
    Type: String

  VersionedBucketName:
    Type: String
    Default: lambda-uploads

Resources:
  VersionedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${Unique}--${VersionedBucketName}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            Id: "lambda version expiration rule"
            # Don't use ExpirationIn Days. It will expire the current version
            # which will break the Makefile when it tries to get a version ID.
            #           ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
              NewerNoncurrentVersions: 3

Outputs:
  BucketName:
    Value: !Sub "${Unique}--${VersionedBucketName}"
