# create-stack --stack-name simple-lambda --template-body file://simple-lambda.yml --capabilities CAPABILITY_NAMED_IAM
# ...wait a while...
# aws cloudformation list-stacks
# ...to see if it's been created...
# aws lambda invoke --invocation-type RequestResponse --function-name simple-lambda out.txt
# cat out.txt
# rm out.txt
# ...explore stack, lambda, role in the console if so inclined...
# aws cloudformation delete-stack --stack-name simple-lambda
AWSTemplateFormatVersion: 2010-09-09
Description: Exploring AWS HTTP API Gateway

Parameters:

  LambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: simple-lambda

Resources:

  SimpleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
#      ManagedPolicyArns: 
#       - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  SimpleLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Role: !GetAtt SimpleLambdaRole.Arn
      Runtime: python3.9
      Handler: index.handler
      Code:
        ZipFile: |
          import json

          def handler(event, context):
            return {
              'statusCode': 200,
              'body': json.dumps('Hello from simple-lambda!')
            }
      MemorySize: 128
      Timeout: 30
